version: '3'
services: 
  apache:
    build: apache/
    ports: 
      - 80:80
    volumes:
      - ./src:/var/www/html
    networks:
      - frontend
      - backend

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=proyecto
      - MYSQL_USER=lamp_user
      - MYSQL_PASSWORD=lamp_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - backend
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8181:80
    environment:
      - PMA_HOST=mysql
    depends_on: 
      - mysql 
    networks:
      - frontend
      - backend
volumes:
  mysql_data:
networks:
  frontend:
  backend:
